server:
    port: 8443
    ssl:
        enabled: true
        key-store: classpath:keystore.p12
        key-store-password: 1234567890
        key-store-type: PKCS12
        key-alias: myalias
    shutdown: graceful

ftps:
    config-map:
        host: '13.234.135.192'
        port: 990
        username: 'ftpsuser'
        password: 'd#xt54Z2oU'
        useImplicit: true
        requireClientCert: true
        READ_ROOT_PATH: ''

mqtt:
    config-map:
        host: 'mosquitto.sre.turtle-feature.com'
        port: 8883
        publishUsername: 'publisher_elecbits'
        publishPassword: 'PubElec!bE@ts437#9'
        subscribeUsername: 'subscriber_elecbits'
        subscribePassword: '$ubElec!bE@ts202#9'